WEB_SOCKET_CATEGORY_DICT = {
    "ALL_DATA": "ALL_DATA",
    "MESSAGE": "MESSAGE",
    "FILE": "FILE",
    "CLIPBOARD": "CLIPBOARD"
}

WEB_SOCKET_CATEGORY_LIST = {
    "MESSAGE": "MESSAGE",
    "FILE": "FILE",
    "CLIPBOARD": "CLIPBOARD"
}